#!/bin/bash
#
# This script performs on backup cycle. A cron job will be used
# to tell this script when to run therby generating the cycle.
#
rm -f -r /home/def_user/backup/bk_wip/*

mv /home/def_user/backup/current/*.tar.gz /home/def_user/backup/last/

find /home/def_user/backup/last -maxdepth 1 -type f -name "*.tar.gz" -print0 | xargs -r0 ls -t | tail -n +16 | tr '\n' '\0' | xargs -r0 rm

mysqldump -u root -pG0nefishin 1bd3e0294da19198 | gzip > /home/def_user/backup/bk_wip/db_bkup.sql.gz

tar -czf /home/def_user/backup/bk_wip/pri-files.tar.gz -C /home/def_user/frappe-bench/sites/site1.local/private/files .

tar -czf /home/def_user/backup/bk_wip/pub-files.tar.gz -C /home/def_user/frappe-bench/sites/site1.local/public/files .

tar -czf /home/def_user/backup/current/"$(date '+%m%d-%H%M').tar.gz" -C /home/def_user/backup/bk_wip .

scp /home/def_user/backup/current/*.tar.gz def_user@192.168.222.111:/home/def_user/drop/

# This should complete the cycle
# BKM - Apr 08,2019 @ 2:24pm
