#!/bin/sh
#

rm /home/def_user/frappe-next/sites/site1.local/private/files/*
rm /home/def_user/frappe-next/sites/site1.local/prublic/files/*
tar -xzf /home/def_user/local_restore/pri-files.tar.gz -C /home/def_user/frappe-bench/sites/site1.local/private/files/
tar -xzf /home/def_user/local_restore/pub-files.tar.gz -C /home/def_user/frappe-bench/sites/site1.local/public/files/

# This should complete the extraction of files to private abd public files directories
# BKM - Aug 18,2018 @ 3:48pm

